name: P001_final
parameters:
  datamodule:
    parameters:
      data_dir: 
        value: "C:\\Users\\msi\\Desktop\\Constanze\\Docs\\DATA\\PREPROCESSED\\PREP_MINIMAL"
      # val_run: 
      #   value: "/Users/arnavkapur/Desktop/EEG_Speech/DATA/PREPROCESSED/S01/eeg.npy"
      # batch_size:
      #    values: 32
      # binary_classes: ## ADD THIS only for 2 class classification
      #   value: [0,1]
      num_workers:
        value: 0
      seed:
        value: 42

