name: P001_final
parameters:
  datamodule:
    parameters:
      data_dir: 
        value: "/Users/arnavkapur/Desktop/EEG_Speech/DATA/PROCESSING_CHISCO/EEG_NET_Format"
      # val_run: 
      #   value: "/Users/arnavkapur/Desktop/EEG_Speech/DATA/PREPROCESSED/S01/eeg.npy"
      batch_size:
        values: [32, 64, 128] #[32, 128]
      num_workers:
        value: 4
      seed:
        value: 42